### ISSUE TITLE
UI Discussion + Comments + Mock-Ups

### ISSUE THREAD

**Issue by Jusctsch5** [Wilfcastle/colonies#8]
We need to make a handful of decisions on how we're going to handle the UI for colonies. First, we have to decide on what set of libraries we're going to use. Python can be embedded in a number of different programming languages, so most other UIs are on the table. Here are a couple options:

PyGame is the most straight-forward option, but it has limitations and is less popular.
Unity with embedded IronPython is more complicated, but more people use Unity than pygame.
Regardless of the UI, we have to determine how we are going to make use of it.

We need images (sprites, animations, models, etc) for all of the game elements. We need a way to create a visual game board that can adjust to different sizes.
We will need a menu to allow the user to choose a level and provide a limit number of configurable options such as number of players.
We will also need a UI for the game itself. We need to design how the UI will function using a mouse (or other device) to choose a piece and location to clone or jump it.
Please consider the different options and reply on this wiki in the form of comments.

**Comment by golmschenk** [comment]
We have decided on a web interface based on Django.
